# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('4b9ce44a-dca3-4f04-9d1f-5b3076f7dbd0'), editable=False, primary_key=True, serialize=False)),
                ('snumber', models.CharField(blank=True, max_length=255)),
                ('spasswd', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
