# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hellowechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicuser',
            name='snumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magicuser',
            name='spasswd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magicuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ccddd3d4-f0b7-41e5-a671-39ca924c2a69'), editable=False, primary_key=True, serialize=False),
        ),
    ]
