# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hellowechat', '0004_auto_20180203_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicuser',
            name='openid',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='magicuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d39678ed-4e96-4060-af80-6394206185cb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
