# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hellowechat', '0005_auto_20180203_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicuser',
            name='sgrades',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='magicuser',
            name='sjidian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='magicuser',
            name='slessons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magicuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e53e4086-53b5-4d4b-8e50-a671e77fcdc1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
