# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hellowechat', '0007_auto_20180311_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='magicroom',
            name='day',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='magicuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8adfd72b-3640-4fcd-a52d-e1fc4ebd5f91'), editable=False, primary_key=True, serialize=False),
        ),
    ]
