# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellowechat', '0008_auto_20180311_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicroom',
            name='day',
        ),
        migrations.RemoveField(
            model_name='magicroom',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='magicroom',
            name='updatetime',
        ),
        migrations.AddField(
            model_name='magicroom',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='magicroom',
            name='rooms',
            field=models.CharField(blank=True, max_length=6553500, null=True),
        ),
        migrations.AlterField(
            model_name='magicuser',
            name='uuid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
