# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellowechat', '0009_auto_20180315_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicroom',
            name='rooms',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
