# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellowechat', '0010_auto_20180315_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
